// netlify/functions/lib/rla-prompt.js
//
// THE LISTING AGREEMENT (RLA) EXTRACTION INSTRUCTIONS, in one place.
//
// Until 2026-10-09 these lived in index.html and the page sent them along with
// every RLA upload as `prompt_override`. Keeva's listing wizard now reads RLAs
// through this extractor too, so the instructions moved here: the page sends
// `kind: 'rla'` and submit.js / keeva-extract-submit.js attach this prompt.
// One copy, so a fix to the RLA reading reaches both.
//
// Edit with care (see the rla-listing-extraction notes): a key in the JSON
// skeleton with no guidance paragraph tends to come back blank, and every key
// needs an entry in RLA_FIELD_LABELS in index.html to show on the page.

const RLA_PROMPT = `Extract all of the following fields from the uploaded California Residential Listing Agreement and supporting documents. Cross-reference all documents to fill gaps. Return ONLY valid JSON with exactly these keys, no preamble, no markdown:
{"property_address":"","property_type":"","county":"","city":"","zip_code":"","apn":"","sqft_structure":"","sqft_lot":"","year_built":"","hoa_name":"","hoa_fee":"","seller_names":"","seller_1":"","seller_2":"","seller_3":"","seller_4":"","seller_entity_name":"","seller_type":"","seller_signer_1":"","seller_signer_2":"","seller_signer_3":"","seller_signer_4":"","seller_email":"","seller_email_1":"","seller_email_2":"","seller_email_3":"","seller_email_4":"","listing_price":"","listing_date":"","listing_expiration_date":"","listing_agent_commission":"","seller_agent_name":"","seller_agent_dre":"","seller_agent_brokerage":"","seller_agent_brokerage_dre":"","seller_agent_address":"","seller_agent_email":"","seller_agent_phone":""}
Use ISO format YYYY-MM-DD for all dates. For property_type always use SUB TYPE from MLS or Type from Property Profile — valid values: SFR, Condo, Probate, Revocable Trust, Vacant Land, Mobile Home, New Construction, Commercial, Duplex, Triplex, Quadruplex. Normalize all text to proper case. Leave fields as empty string if not found.
SELLER NAMES: seller_names is the combined seller name(s), each in natural First-Last order (rebuild any Last-First source into First-Last); preserve the source separator between distinct sellers; for an entity copy the full entity name as-is; seller_names must never be blank. ALSO split the sellers into seller_1, seller_2, seller_3, seller_4 — ONE human or ONE entity per slot. Rules: a couple sharing a surname like 'Altenbern William & Mary' or 'William & Mary Altenbern' means TWO people → seller_1 'William Altenbern', seller_2 'Mary Altenbern'. Two sellers with different surnames like 'William Chase Altenbern, Mary Elizabeth Kelly' → seller_1 'William Chase Altenbern', seller_2 'Mary Elizabeth Kelly'. An entity (LLC, trust, estate, corporation) is ONE legal seller filling exactly ONE slot intact regardless of how many trustees/members it has (e.g. 'Smith Family Trust' → seller_1 'Smith Family Trust'). Up to 4 sellers. seller_1 is never blank; unused slots are empty string.
SELLER TYPE / ENTITY: seller_type is exactly one of Individual, Trust, LLC, Estate, Power of Attorney (default Individual if unclear; '(Tr)'/'(Te)'/'Trustee' or a name ending in 'Trust' → Trust; '(LLC)' or a name ending in 'LLC' → LLC; 'Estate of' → Estate). seller_entity_name is the full legal entity name when the seller is a trust/LLC/estate/corporation, empty string for individuals. When the seller is an ENTITY, capture the actual HUMAN signers (the trustees/members/officers who sign on behalf of the entity) in seller_signer_1, seller_signer_2, seller_signer_3, seller_signer_4 from the listing agreement signature section — real people, not the entity name; empty string for individual sellers and for unused slots.
LISTING PRICE: format listing_price as US currency with a leading dollar sign and thousands separators, e.g. '$699,000'. Same money format for listing_agent_commission when it is a dollar amount (leave it as a percentage like '2.5%' if it is expressed as a percentage).
SQUARE FOOTAGE: copy sqft_structure and sqft_lot DIRECTLY from the Property Profile, exactly as written. Preserve the commas, the 'sqft' label, and any 'Tax: 1,245 sqft MLS: 2,500 sqft' style breakdown. Do NOT reformat, strip labels/units, recompute, or change anything — reproduce the source text verbatim.
LISTING AGENTS: the listing agent(s) are the "By (Broker/Agent)" lines in the BROKER SIGNATURE(S) block on the last page. When MORE THAN ONE agent signs there (two "By (Broker/Agent)" lines, or a co-listing agent), put ALL of them in seller_agent_name joined with ' / ' in the order they appear (e.g. 'Simon Mashian / Jonathan Carr'), and put their DRE numbers, emails and phones in seller_agent_dre, seller_agent_email and seller_agent_phone joined with ' / ' in the SAME order, one value per agent, so each stays with the right person. seller_agent_brokerage is the firm on the 'Real Estate Broker (Firm)' line (once) and seller_agent_brokerage_dre its DRE Lic #. Never put a seller in these fields.
SELLER EMAIL: the seller email addresses are in the SIGNATURE BLOCK on the LAST page of the listing agreement (RLA page 7 of 7), and that block carries NO field labels — it is a bare run of seller name then seller email, repeated per seller, e.g. 'Seema Bansai / seemavef1991@gmail.com / Sanjam Chadha / sunnyvef89@gmail.com'. Put each seller's own address in seller_email_1, seller_email_2, seller_email_3, seller_email_4, matching the SAME ORDER as seller_1..seller_4 so every address stays attached to the right person; leave a slot empty when that seller gave no address. ALSO set seller_email to all of them joined with ', ' in the same order (a single seller means seller_email equals seller_email_1). NEVER put an agent's or brokerage's address in these fields: further down the same block sits the LISTING AGENT, recognisable because their entry is accompanied by a phone number, a DRE license number and the brokerage name (e.g. 'Evan Dolmatsky / (310)384-2496 / hello@evandolmatsky.com / 01968687') — that address is seller_agent_email, not a seller's. A seller address is the one that follows a SELLER NAME with no phone or license number beside it. When the seller is an entity, use the address of the human who signed for it. Do not invent or normalise an address: copy it character for character, and leave the field empty if it is genuinely absent.`;

module.exports = { RLA_PROMPT };
